"""
AI report generation routes (Groq LLM).
=======================================

Turns real district / national data into downloadable, print-ready HTML
intelligence products (CAG-format case files, national briefs, scorecards).
"""

from __future__ import annotations

import base64
import re
from datetime import datetime
from typing import Any, Dict

from fastapi import APIRouter, HTTPException
from pydantic import BaseModel

from services import india_data, llm, pdf

router = APIRouter(prefix="/api/ai", tags=["AI Reports"])


def _slug(s: str) -> str:
    return re.sub(r"[^a-z0-9]+", "-", s.lower()).strip("-")


def _wrap_html(title: str, subtitle: str, fragment: str, source_note: str) -> str:
    """Wrap an HTML fragment in a print/PDF-friendly government document.

    CSS is kept to the subset xhtml2pdf supports (no gradients/flexbox); the
    tricolor band is a 3-cell table so it renders identically in the PDF.
    """
    now = datetime.now().strftime("%d %B %Y, %H:%M")
    return f"""<!doctype html>
<html lang="en"><head><meta charset="utf-8"><title>{title}</title>
<style>
  @page {{ size: a4; margin: 1.8cm 1.6cm; }}
  body {{ font-family: Helvetica, Arial, sans-serif; color: #14203f; font-size: 11pt; line-height: 1.5; }}
  h1 {{ font-size: 19pt; margin: 4px 0 2px; color: #0b1f4d; }}
  h2 {{ font-size: 13pt; border-bottom: 1px solid #cdd6ea; padding-bottom: 3px; margin-top: 18px; color: #0b1f4d; }}
  h3 {{ font-size: 11.5pt; color: #213a6b; margin-top: 12px; }}
  .gi {{ font-size: 8.5pt; letter-spacing: 1px; color: #8a6d3b; }}
  .sub {{ color: #5a6473; font-size: 9.5pt; }}
  table {{ border-collapse: collapse; width: 100%; margin: 8px 0; font-size: 9.5pt; }}
  th, td {{ border: 1px solid #dde2ee; padding: 5px 8px; text-align: left; }}
  th {{ background-color: #eef3fb; }}
  ul {{ margin: 6px 0 6px 16px; }}
  .tri td {{ border: none; padding: 0; height: 5px; }}
  .badge {{ background-color: #fff3e0; color: #b25b00; font-weight: bold; font-size: 8.5pt; padding: 2px 8px; }}
  footer {{ margin-top: 26px; border-top: 1px solid #e5e8f0; padding-top: 8px; color: #7a8499; font-size: 8pt; }}
</style></head>
<body>
  <table class="tri" width="100%"><tr>
    <td width="33%" bgcolor="#ff9933"></td><td width="34%" bgcolor="#ffffff"></td><td width="33%" bgcolor="#138808"></td>
  </tr></table>
  <div class="gi">GOVERNMENT OF INDIA &middot; MINISTRY OF RURAL DEVELOPMENT</div>
  <h1>{title}</h1>
  <div class="sub">{subtitle} &middot; Generated {now}</div>
  <p><span class="badge">MGNREGA National Verification System</span></p>
  {fragment}
  <footer>
    {source_note}<br/>
    Generated by the MGNREGA NVS AI engine (Groq &middot; {llm.model_name()}).
    Decision-support document; figures must be confirmed against source MIS records before audit action.
  </footer>
</body></html>"""


def _finalize(filename_base: str, title: str, subtitle: str,
              fragment: str, source_note: str, model: str) -> Dict[str, Any]:
    """Build the document, render to PDF (fallback to HTML), return response."""
    html = _wrap_html(title, subtitle, fragment, source_note)
    pdf_bytes = pdf.html_to_pdf(html)
    if pdf_bytes:
        return {
            "filename": f"{filename_base}.pdf",
            "pdf_base64": base64.b64encode(pdf_bytes).decode("ascii"),
            "model": model,
        }
    # graceful fallback if PDF rendering fails for any reason
    return {"filename": f"{filename_base}.html", "html": html, "model": model}


class GenResponse(BaseModel):
    filename: str
    model: str
    pdf_base64: str | None = None
    html: str | None = None


@router.get("/status", summary="Is the AI engine configured?")
async def ai_status() -> Dict[str, Any]:
    return {"configured": llm.is_configured(), "model": llm.model_name() if llm.is_configured() else None}


@router.post("/case-file/{district_id}", response_model=GenResponse, summary="Generate a district case file")
async def case_file(district_id: str) -> Dict[str, Any]:
    if not llm.is_configured():
        raise HTTPException(503, "AI engine not configured (set GROQ_API_KEY).")
    d = india_data.get_district(district_id)
    if not d:
        raise HTTPException(404, f"District {district_id} not found")
    try:
        fragment = await llm.generate_case_file_html(d)
    except Exception as exc:
        raise HTTPException(502, f"LLM generation failed: {exc}")

    src = ("Figures are LIVE from data.gov.in / NREGA MIS."
           if d.get("data_source", "modelled") != "modelled"
           else "NOTE: District figures are currently MODELLED for demonstration; "
                "connect a live source to replace them.")
    return _finalize(
        filename_base=f"case-file-{_slug(d['district_name'])}-2025-26",
        title=f"MGNREGA Verification Case File - {d['district_name']}",
        subtitle=f"{d['state_name']} &middot; FY 2025-26 &middot; Composite risk {d.get('risk_score')}",
        fragment=fragment, source_note=src, model=llm.model_name(),
    )


class ReportRequest(BaseModel):
    kind: str = "national-brief"


@router.post("/report", response_model=GenResponse, summary="Generate a national/strategic report")
async def report(req: ReportRequest) -> Dict[str, Any]:
    if not llm.is_configured():
        raise HTTPException(503, "AI engine not configured (set GROQ_API_KEY).")

    n = india_data.national_summary()
    context = {
        "fin_year": "2025-26",
        "states": n.get("total_states"), "uts": n.get("total_uts"),
        "districts": n.get("total_districts"),
        "outlay_rs_crore": round((n.get("total_expenditure_lakhs") or 0) / 100),
        "person_days_crore": round((n.get("person_days") or 0) / 1e7, 1),
        "total_works": n.get("total_works"),
        "flagged_works": n.get("flagged_count"),
        "anomalies": n.get("anomalies_count"),
        "estimated_leakage_rs_crore": round((n.get("estimated_leakage_lakhs") or 0) / 100),
        "national_composite_risk": n.get("risk_score"),
        "anomaly_by_type": n.get("anomaly_by_type"),
        "top_risk_districts": [
            {"district": d["district_name"], "state": d["state_name"], "risk": d["risk_score"]}
            for d in india_data.top_risk_districts(10)
        ],
    }
    titles = {
        "national-brief": "National MGNREGA Intelligence Brief",
        "scorecard": "State Performance Scorecard",
        "audit-pack": "CAG-Format Audit Summary",
        "dpc-briefing": "Weekly DPC Briefing",
    }
    title = titles.get(req.kind, "MGNREGA Intelligence Report")
    brief = "Summarise national fraud posture, regional hotspots and recommended actions."
    try:
        fragment = await llm.generate_report_html(title, context, brief)
    except Exception as exc:
        raise HTTPException(502, f"LLM generation failed: {exc}")

    src = "NOTE: Aggregate figures include modelled district data for demonstration."
    return _finalize(
        filename_base=f"{_slug(title)}-2025-26", title=title,
        subtitle="All-India &middot; FY 2025-26", fragment=fragment,
        source_note=src, model=llm.model_name(),
    )
